"""SPEC-01 §1: strategy enums."""

from __future__ import annotations

from enum import StrEnum


class DecisionOutcome(StrEnum):
    TRADE = "TRADE"
    WAIT = "WAIT"


class EvidenceType(StrEnum):
    HTF_TREND_ALIGNMENT = "HTF_TREND_ALIGNMENT"
    LIQUIDITY_SWEEP = "LIQUIDITY_SWEEP"
    STRUCTURE_BREAK = "STRUCTURE_BREAK"
    RETEST_CONFIRMED = "RETEST_CONFIRMED"
    SR_ZONE = "SR_ZONE"
    FIB_GOLDEN_ZONE = "FIB_GOLDEN_ZONE"
    CANDLE_CONFIRMATION = "CANDLE_CONFIRMATION"
    VOLUME_CONFIRMATION = "VOLUME_CONFIRMATION"
    MANIPULATION_QUALITY = "MANIPULATION_QUALITY"
    MOMENTUM_EXPANSION = "MOMENTUM_EXPANSION"
    VOLATILITY_REGIME = "VOLATILITY_REGIME"
    SESSION_QUALITY = "SESSION_QUALITY"


class GateCode(StrEnum):
    # market and connectivity
    MARKET_CLOSED = "MARKET_CLOSED"
    PRICE_STALE = "PRICE_STALE"
    AGENT_DISCONNECTED = "AGENT_DISCONNECTED"
    BROKER_DISCONNECTED = "BROKER_DISCONNECTED"
    RECONCILIATION_UNRESOLVED = "RECONCILIATION_UNRESOLVED"
    # cost and quality
    SPREAD_TOO_WIDE = "SPREAD_TOO_WIDE"
    VOLATILITY_OUT_OF_BOUNDS = "VOLATILITY_OUT_OF_BOUNDS"
    SESSION_NOT_PERMITTED = "SESSION_NOT_PERMITTED"
    NEWS_BLACKOUT = "NEWS_BLACKOUT"
    # risk
    DAILY_LOSS_LIMIT = "DAILY_LOSS_LIMIT"
    WEEKLY_LOSS_LIMIT = "WEEKLY_LOSS_LIMIT"
    MAX_DAILY_TRADES = "MAX_DAILY_TRADES"
    MAX_OPEN_POSITIONS = "MAX_OPEN_POSITIONS"
    MAX_OPEN_RISK = "MAX_OPEN_RISK"
    CORRELATED_EXPOSURE = "CORRELATED_EXPOSURE"
    INSUFFICIENT_MARGIN = "INSUFFICIENT_MARGIN"
    # setup quality
    RR_BELOW_MINIMUM = "RR_BELOW_MINIMUM"
    STOP_DISTANCE_INVALID = "STOP_DISTANCE_INVALID"
    CONFLUENCE_BELOW_THRESHOLD = "CONFLUENCE_BELOW_THRESHOLD"
    DUPLICATE_SETUP = "DUPLICATE_SETUP"
    REGIME_NOT_PERMITTED = "REGIME_NOT_PERMITTED"
    # control
    TRADING_DISABLED = "TRADING_DISABLED"
    KILL_SWITCH_ACTIVE = "KILL_SWITCH_ACTIVE"
    STRATEGY_PAUSED = "STRATEGY_PAUSED"
